services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/media:/app/media
      - ./backend/static:/app/statics
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
