# Generated by Django 5.1.3 on 2024-11-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("namas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
